server:
 port: 8082
spring:
  datasource:
    username: mixchain
    password: 123456
    url: jdbc:mysql://120.25.86.135:3306/mixchain?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/static/


#mybatis配置
#首先是实体类所在的包的名字
mybatis:
    type-aliases-package: com.example.wallet.manage.entity
    mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2.xml
  level:
    root: debug